### ISSUE TITLE
[FEATURE REQUEST] Option for picking already taken pictures

### ISSUE THREAD

**Issue by RafeeDaBoy** [ptrLx/OneShot#2]
Hi, the app has a very cool idea and I absolutely love it. I think it'd be very useful if there was an option to pick a picture from gallery.

Uses:
1. Pictures from other apps with camera filters.
2. Picking a picture from a memorable moment that happened earlier that day

I feel like it gives a bit more control to the user to customize their diary and make it more personal.

**Comment by ptrLx** [comment]
I have two thoughts on this:

* the app is meant to take a photo and leave it again. You shouldn't spend unnecessary time in it to capture what you think is the best photo of the day and compare photos with each other. One shot and go. it's much more about having one nice memory per day in the long run.

* The photos from oneshot are stored in a separate/any folder in the system. A file picker would have to be implemented so that the photo is copied into the oneshot folder, if it is not the same folder anyway. Then you would have the photo twice.

But there are elegant solutions for this. ;) I am not averse to the feature in general.

**Comment by RafeeDaBoy** [comment]
Oh okay that's great to know! Also, I had another feature in mind. 

- In the diary section, it'd be nice if voice memos could also be added along with text.
